version: "3.1"
services:

  frontend:
    container_name: tarefas-frontend
    build: ./frontend
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - '80:80'
    environment:
      - NODE_ENV=development
    depends_on: 
      - backend

  backend:
    container_name: tarefas-backend
    restart: always
    build: ./backend
    ports:
      - '4000:4000'
    command: [yarn, start]
    depends_on: 
      - mongo

  mongo:
    image: mongo
    restart: always
    container_name: tarefas-mongodb
    volumes:
      - ./mongodb/data:/data/db
    ports:
      - 27017:27017
    command: mongod