version: "3.1"
services:

  backend:
    container_name: tarefas-backend
    restart: always
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
      - ./backend/node_modules:/usr/src/app/node_modules
    ports:
      - '4000:4000'
    command: [yarn, start]
  
  frontend:
    container_name: tarefas-frontend
    build: ./frontend
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    links:
      - backend
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - '80:80'
    environment:
      - NODE_ENV=development

  mongo:
    image: mongo
    restart: always
    container_name: tarefas-mongodb
    ports:
      - 27017:27017
    command: mongod